@startuml
[*] --> Created : Job created

state Cancelled #LightGray
note right of Cancelled
  This state is planned for future release.
end note

state TimedOut #LightGray
note right of TimedOut
  This state is planned for future release.
end note

Created --> Scheduled : Job queued
Scheduled --> Processing : Job started
Processing --> Completed : Job completed successfully
Processing --> Terminated : Job encountered an error
Terminated --> Scheduled : [if recurring or recurring] Reschedule
Completed --> Scheduled : [if recurring] Reschedule
Terminated --> [*] : [if not retriable and not recurring]
Completed --> [*] : [if not recurring]

Processing --> Cancelled : Job was cancelled
Cancelled --> [*]
Processing --> TimedOut : Job exceeded time limit
TimedOut --> Scheduled : [if retriable] Reschedule
TimedOut --> [*] : [if not retriable and not recurring]

@enduml