@startuml

participant Client

box "Server Components" #LightBlue
    participant Manager
    participant Registry
    participant Scheduler
    participant Worker
    participant Queue
    participant History
    participant Log
end box

box "Plugin Component" #LightBlue
    participant Store
end box

== Register Job ==

Client -> Manager : Register Job
Manager -> Registry : Register Job

== Query Registered Jobs ==

Client -> Manager : Query Registered Jobs
Manager -> Registry : Query Registered Jobs
Registry -> Manager : Response Registered Jobs
Manager -> Client : Response Registered Jobs

== Schedule Job Instance ==

Client -> Manager : Schedule Job Instance
Manager -> Registry : Query Job
Registry -> Manager : Response Job
Manager -> Scheduler : Schedule Job　Instance
Scheduler -> Scheduler : Create Job Instance
Scheduler -> Queue : Enqueue Job Instance
Queue -> Store : Enqueue Job Instance

== Process Job Instance ==

Worker -> Queue : Dequeue Job Instance
Store --> Queue : Dequeue Job Instance
Queue --> Worker : Dequeue Job Instance
Worker -> History : Update Job State
Worker -> Worker : Execute Job Instance
Worker -> History : Update Job State
History -> Store : Update Job State
Worker -> Log : Log message
Log -> Store : Log message
Worker --> Client : Notify Job Completion or Termination

== Query Job Execution History ==

Client -> Manager : Query Job State History
Manager -> History : Query Job State History
History -> Store : Query Job State History
Store -> History : Response Job State History
History -> Manager : Response Job State History
Manager -> Client : Response Job State History

Client -> Manager : Query Job logs
Manager -> Log : Query Job logs
Log -> Store : Query Job logs
Store -> Log : Response Job logs
Log -> Manager : Response Job logs
Manager -> Client : Response Job logs

@enduml