@startuml
[*] --> Created : Job created

Created --> Scheduled : Job queued
Scheduled --> Processing : Job started
Processing --> Completed : Job completed successfully
Processing --> Terminated : Job encountered an error
Terminated --> Scheduled : [if recurring or recurring] Reschedule
Completed --> Scheduled : [if recurring] Reschedule
Terminated --> [*] : [if not retriable and not recurring]
Completed --> [*] : [if not recurring]

Processing --> Cancelled : Job was canceled
Cancelled --> [*]
Processing --> TimedOut : Job exceeded time limit
TimedOut --> Scheduled : [if retriable] Reschedule
TimedOut --> [*] : [if not retriable and not recurring]

@enduml