@startuml

== Register Job  ==

Client -> Manager : Register Job
Manager -> Registry : Register Job

== Schedule Job Instance ==

Client -> Manager : Schedule Job Instance
Manager -> Scheduler : Schedule Job Instance
Manager -> Registry : Query Job
Registry -> Manager : Response Job
Scheduler -> Scheduler : Create Job Instance
Scheduler -> Queue : Enqueue Job Instance

== Process Job Instance ==

Queue --> Worker : Dequeue Job Instance
Worker -> History : Update Job State
Worker -> Worker : Execute Job Instance
Worker -> History : Update Job State
Worker --> Client : Notify Job Completion

== Query Job Instance State  ==

Client -> History : Query Job Instance State
History -> Client : Return Job Instance State

@enduml