@startuml

object Job{
  +Kind: String
}

object JobInstance {
  History: JobStateHistory
  +Kind: String
  +UUID: uuid.UUID
  +status: String
  +createdAt: DateTime
  +updatedAt: DateTime
}

History -> JobStateHistory

JobInstance --|> Job

object Manager {
  +Kind: String
  +UUID: uuid.UUID
  +status: String
  +createdAt: DateTime
  +updatedAt: DateTime
}

object JobStateHistory {
  +UUID: uuid.UUID
  +status: String
  +createdAt: DateTime
  +updatedAt: DateTime
}

@enduml