@startuml

object Job{
  +Kind: String
}

object JobInstance {
  History: JobStateHistory -- JobStateHistory
}

History -> JobStateHistory

object Manager {
}

object JobStateHistory {
  +Records(): []JobStateRecord -- JobStateRecord
}

object JobStateRecord {
  +Timestamp(): time.Time
  +State(): JobState
}

@enduml