@startuml

object Job {
  +Kind: String
}

object Instance {
  History: StateHistory -- StateHistory
}

History -> StateHistory

object Manager {
}

object Scheduler {
}

object StateHistory {
  +Records(): []StateRecord -- StateRecord
}

object StateRecord {
  +Timestamp(): time.Time
  +State(): JobState
}

@enduml