@startuml

== Schedule Job ==

Client -> Manager : Schedule Job
Manager -> Schedular : Schedule Job
Schedular -> Schedular : Create Job Instance
Schedular -> Queue : Enqueue Job Instance

== Process Job ==

Queue --> Worker : Dequeue Job Instance
Worker -> History : Update Job State
Worker -> Worker : Execute Job Instance
Worker -> History : Update Job State
Worker --> Client : Notify Job Completion

== Query Job State ==

Client -> History : Query Job State
History -> Client : Return Job State

@enduml