name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      valkey:
        image: valkey/valkey:8.1.3
        ports:
          - 6379:6379
      etcd:
        image: gcr.io/etcd-development/etcd:v3.6.4
        ports:
          - 2379:2379
          - 2380:2380
        env:
          ETCD_NAME: etcd0
          ETCD_DATA_DIR: /etcd-data
          ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
          ETCD_ADVERTISE_CLIENT_URLS: http://127.0.0.1:2379
          ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
      - name: Set up golangci-lint
        run: sudo snap install golangci-lint --classic
      - name: Install
        run: make install
      - name: Test
        run: make test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: job-cover.out
